### PR TITLE
refactor: Remove old and obsolete lsts

### LINKED ISSUE #68: Remove old and unneeded lst files
Really old versions of Zend Server and Power Ruby an xlc could be removed, possibly more.

### PR DESCRIPTION
**Pull request by abmusse**
Fixes #68

### CODE REVIEW

**Comment by abmusse** [comment]
We should also consider removing [chroot_system.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_system.lst) looks like its main use was to call change authority of chroot to a user using variable substituation. No sure if anyone is even using this lst currently. At least we should rename it to something more meaningful.

**Review by kadler — COMMENTED** [review]
chroot_bins and chroot_libs are not used?

**Comment by abmusse** [comment]
Both the files are essentially commented out and state there are obsoleted by chroot_minimal.lst:

```
# Note: This file is obsolete, use chroot_minimal

```

**Comment by kadler** [comment]
Oh, I missed that. LGTM then.

**Review by kadler — APPROVED** [review]

**Pull request merged**
